export const SIGNUP = 'SIGNUP';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL ="LOGIN_FAIL";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";


//book a ticket
export const BOOK_TICKET = 'BOOK_TICKET';
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS';
export const BOOKING_FAIL = "BOOKING_FAIL";

// Get moview details
export const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_DETAIL_SUCCESS";
export const GET_MOVIE_DETAIL_FAILURE = "GET_MOVIE_DETAIL_FAILURE";
export const MOVIE_STAR_SUCCESS = "MOVIE_STAR_SUCCESS";
export const MOVIE_STAR_FAILURE = "MOVIE_STAR_FAILURE";
export const GET_MOVIE_REVIEWERS_SUCCESS="GET_MOVIE_REVIEWERS_SUCCESS";
export const GET_MOVIE_REVIEWERS_FAILURE="GET_MOVIE_REVIEWERS_FAILURE";
export const SUBMIT_MOVIE_COMMENT_SUCCESS ="SUBMIT_MOVIE_COMMENT_SUCCESS";
export const SUBMIT_MOVIE_COMMENT_FAILURE ="SUBMIT_MOVIE_COMMENT_FAILURE";
export const GET_MOVIE_HALL_TIMES_SUCCESS="GET_MOVIE_HALL_TIMES_SUCCESS";
export const GET_MOVIE_HALL_TIMES_FAILURE="GET_MOVIE_HALL_TIMES_FAILURE";
