export const SIGNUP = 'SIGNUP';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL ="LOGIN_FAIL";

//book a ticket
export const BOOK_TICKET = 'BOOK_TICKET';
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS';
export const BOOKING_FAIL = "BOOKING_FAIL";

// Get moview details
export const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_DETAIL_SUCCESS";
export const GET_MOVIE_DETAIL_FAILURE = "GET_MOVIE_DETAIL_FAILURE";
export const MOVIE_STAR_SUCCESS = "MOVIE_STAR_SUCCESS";
export const MOVIE_STAR_FAILURE = "MOVIE_STAR_FAILURE";
export const GET_MOVIE_REVIEWERS_SUCCESS="GET_MOVIE_REVIEWERS_SUCCESS";
export const GET_MOVIE_REVIEWERS_FAILURE="GET_MOVIE_REVIEWERS_FAILURE";

